### PR TITLE
Added support for coveralls

### PR DESCRIPTION
**Pull request by tethryus**
Testing coveralls support

Signed off by Sorin Moldovan: <sorin.moldovan@hpe.com>

### CODE REVIEW

**Comment by victorursan** [comment]
@tethryus I don't think 14 commits with the message: "Update" is very descriptive 😆

**Comment by tethryus** [comment]
@victorursan You`re right. I will commit with the actual message next time.

**Comment by victorursan** [comment]
@tethryus What is the status for this? I really want this up and running ... we should sync up on monday and try to make this run 👍

**Comment by victorursan** [comment]
:+1:

**Comment by Bonczidai** [comment]
👌

**Comment by victorursan** [comment]
it's not ok, the coverage is really low 👎

**Comment by tethryus** [comment]
I agree with @victorursan The coverage should be at least 80%

**Comment by Bonczidai** [comment]
coverage-wise, I agree - it's a problem not only in this repository - IMHO it's a good idea to open an issue

**Pull request merged**
