### PR TITLE
Amazon AWS EC2 - Re-implement actions using Query Api

### PR DESCRIPTION
**Pull request by mihaitusa**
Re-implement using Query API:  instances -> start/stop/reboot/terminate, volumes -> attach/detach/delete, snapshots -> create/delete + lots of cleanup.

### CODE REVIEW

**Comment by mihaitusa** [comment]
@Tirla-Alin Please continue this work.

**Comment by Tirla-Alin** [comment]
@Bonczidai Please review this and add if you have any comments in order to merge it to master.

**Comment by mihaitusa** [comment]
@Tirla-Alin Please add junits for them!

**Comment by lucian-cm** [comment]
Looks good to me 👍  
@Tirla-Alin there are also some conflicts. Please see those too.

**Comment by Tirla-Alin** [comment]
@lucian-cm @Bonczidai merge conflicts were fixed, and i also added unit tests for the operations.

**Pull request merged**
