### PR TITLE
Couchbase - Flush Bucket

### PR DESCRIPTION
**Pull request by mihaitusa**
Couchbase - Flush Bucket - operation && unit test.
Signed off by Tusa Mihai: tusa.mihai@gmail.com

### CODE REVIEW

**Comment by mihaitusa** [comment]
@lrevnic ... a promise is a promise... even later on. If this above is merged I'll come back with more of...

**Comment by mihaitusa** [comment]
@lucian-cm Can this be merged? Is fully functional... I've tested...

**Comment by lrevnic** [comment]
Added my review earlier. Thank you! Merging now!

**Comment by lucian-cm** [comment]
Looks good to me, thanks 👍 @mihaitusa!

**Pull request merged**
